
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Sun Jun 08 00:27:50 CEST 2025
//----------------------------------------------------

package fr.uha.montivincent.jcupnflex.sample.calculator.reader;

/** CUP generated enum containing nonterminal constants. */
public enum ENonterminal {
  /* nonterminals */
  array,
  document,
  input,
  myarrVals,
  pairarray,
  pairkeyval,
  tab,
  tpair,
  compositekey,
  key,
  simplekey,
  value,
  $START,
  input$0_many,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

