
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Sun Jun 08 00:27:50 CEST 2025
//----------------------------------------------------

package fr.uha.montivincent.jcupnflex.sample.calculator.reader;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   OOA,
   EOLN,
   __REGEXP_1__,
   __REGEXP_2__,
   __REGEXP_3__,
   __REGEXP_4__,
   BOOLEAN,
   DOUBLE,
   INTEGER,
   COMMA,
   COMMENT,
   DATE,
   QTDSTR,
   TIME,
   UNQTDSTR,
   ;
}

