
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Mon Jun 02 10:25:05 CEST 2025
//----------------------------------------------------

package fr.uha.hassenforder.logo.reader;

/** CUP generated enum containing nonterminal constants. */
public enum ENonterminal {
  /* nonterminals */
  command,
  definition,
  instruction,
  $START,
  definition$0_many,
   ;
}

