
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Mon Jun 02 10:25:05 CEST 2025
//----------------------------------------------------

package fr.uha.hassenforder.logo.reader;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   OOA,
   __REGEXP_1__,
   ;
}

