
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Mon Jun 02 10:25:05 CEST 2025
//----------------------------------------------------

package fr.uha.montivincent.jcupnflex.sample.calculator.reader;

/** CUP generated enum containing nonterminal constants. */
public enum ENonterminal {
  /* nonterminals */
  command,
  keyval,
  list,
  array,
  array_elements,
  value,
  key,
  type,
  $START,
  keyval$0_1,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

